# Generated by Django 4.2.7 on 2023-12-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
