# Generated by Django 4.2.7 on 2023-12-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_payment_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], default='RUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(verbose_name='Сумма транакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Дата транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_name',
            field=models.CharField(max_length=30, verbose_name='Имя транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(max_length=20, verbose_name='Тип транзакции'),
        ),
    ]
