# Generated by Django 4.2.7 on 2023-12-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_customuser_balance_portfolio_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма транзакции в рублях'),
        ),
    ]
