# Generated by Django 4.2.7 on 2023-12-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], default='RUB', max_length=3),
            preserve_default=False,
        ),
    ]
