# Generated by Django 4.2.7 on 2023-12-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_incomecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='income_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.incomecategory', verbose_name='Категория дохода'),
        ),
    ]
