# Generated by Django 4.2.7 on 2023-12-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_transaction_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='income_category',
        ),
    ]
