# Generated by Django 4.2.7 on 2023-12-22 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_payment_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='portfolio',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dashboard.portfolio'),
            preserve_default=False,
        ),
    ]
